# Changes here will be overwritten by Copier
_commit: 3b7ad1e
_src_path: https://github.com/oarepo/nrp-app-copier
languages: cs
repository_description: Sample Repository
repository_human_name: Sample Repository
